/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package clinicamedicapoo.prontuario;

import javax.swing.JButton;

/**
 *
 * @author João Vitor Malvestio
 */

public class ProntuarioConsultaView extends javax.swing.JFrame {
    private ProntuarioTableModel prontuario_table_model;
    
    public ProntuarioConsultaView(ProntuarioTableModel prontuario_table_model) {
        this.prontuario_table_model = prontuario_table_model;
        initComponents();
        setLocationRelativeTo(null);
    }

    public ProntuarioTableModel getProntuario_table_model() {
        return prontuario_table_model;
    }

    public void setProntuario_table_model(ProntuarioTableModel prontuario_table_model) {
        this.prontuario_table_model = prontuario_table_model;
    }

    public JButton getBtEditarProntuario() {
        return btEditarProntuario;
    }

    public JButton getBtExcluirProntuario() {
        return btExcluirProntuario;
    }

    public JButton getBtFechar() {
        return btFechar;
    }

    public JButton getBtNovoProntuario() {
        return btNovoProntuario;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btNovoProntuario = new javax.swing.JButton();
        btEditarProntuario = new javax.swing.JButton();
        btExcluirProntuario = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btFechar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(prontuario_table_model);
        jScrollPane1.setViewportView(jTable1);

        btNovoProntuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vendor/icons/add.png"))); // NOI18N
        btNovoProntuario.setText("Novo");

        btEditarProntuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vendor/icons/pencil.png"))); // NOI18N
        btEditarProntuario.setText("Editar");

        btExcluirProntuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vendor/icons/cross.png"))); // NOI18N
        btExcluirProntuario.setText("Excluir");

        jLabel1.setText("Manuteção de Prontuarios");

        btFechar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vendor/icons/cancel.png"))); // NOI18N
        btFechar.setText("Fechar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btNovoProntuario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btEditarProntuario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btExcluirProntuario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                        .addComponent(btFechar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btNovoProntuario)
                    .addComponent(btEditarProntuario)
                    .addComponent(btExcluirProntuario)
                    .addComponent(btFechar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btEditarProntuario;
    private javax.swing.JButton btExcluirProntuario;
    private javax.swing.JButton btFechar;
    private javax.swing.JButton btNovoProntuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
