/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package clinicamedicapoo.paciente;

/**
 *
 * @author miche
 */
public class PacienteConsultaView extends javax.swing.JFrame {
    PacienteRegistroView paciente_registro = new PacienteRegistroView();
    /**
     * Creates new form PacienteView
     */
    public PacienteConsultaView() {
        initComponents();
    }
    PacienteController pc = new PacienteController();
    public PacienteTableModel paciente = new PacienteTableModel(pc.getPaciente("%%"));
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jtable_consulta_paciente = new javax.swing.JTable();
        jbutton_adicionar = new javax.swing.JButton();
        jbutton_editar = new javax.swing.JButton();
        jbutton_excluir = new javax.swing.JButton();
        jlabel_filtro_nome = new javax.swing.JLabel();
        jtext_filtro_nome = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setTitle("Consulta Pacientes");

        jtable_consulta_paciente.setModel(paciente);
        jtable_consulta_paciente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtable_consulta_pacienteKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jtable_consulta_paciente);

        jbutton_adicionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vendor/icons/add.png"))); // NOI18N
        jbutton_adicionar.setText("Adicionar");
        jbutton_adicionar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbutton_adicionarMouseClicked(evt);
            }
        });

        jbutton_editar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vendor/icons/pencil.png"))); // NOI18N
        jbutton_editar.setText("Editar");

        jbutton_excluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vendor/icons/cross.png"))); // NOI18N
        jbutton_excluir.setText("Excluir");

        jlabel_filtro_nome.setText("Filtrar:");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vendor/icons/magnifier.png"))); // NOI18N
        jButton1.setText("Pesquisa");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 636, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jlabel_filtro_nome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtext_filtro_nome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addGap(70, 70, 70)
                .addComponent(jbutton_adicionar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbutton_editar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbutton_excluir)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbutton_adicionar)
                    .addComponent(jbutton_editar)
                    .addComponent(jbutton_excluir)
                    .addComponent(jlabel_filtro_nome)
                    .addComponent(jtext_filtro_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtable_consulta_pacienteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtable_consulta_pacienteKeyReleased
        
    }//GEN-LAST:event_jtable_consulta_pacienteKeyReleased

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        paciente = new PacienteTableModel(pc.getPaciente(jtext_filtro_nome.getText()));
        jtable_consulta_paciente.setModel(paciente);
    }//GEN-LAST:event_jButton1MouseClicked

    private void jbutton_adicionarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbutton_adicionarMouseClicked
        if(!paciente_registro.isVisible()){
            paciente_registro.setVisible(true);
        }
    }//GEN-LAST:event_jbutton_adicionarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(javax.swing.UIManager.getSystemLookAndFeelClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PacienteConsultaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PacienteConsultaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PacienteConsultaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PacienteConsultaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PacienteConsultaView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbutton_adicionar;
    private javax.swing.JButton jbutton_editar;
    private javax.swing.JButton jbutton_excluir;
    private javax.swing.JLabel jlabel_filtro_nome;
    private javax.swing.JTable jtable_consulta_paciente;
    private javax.swing.JTextField jtext_filtro_nome;
    // End of variables declaration//GEN-END:variables
}
