/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package clinicamedicapoo.paciente;

import javax.swing.JButton;
import javax.swing.JTable;

/**
 *
 * @author miche
 */
public class SelecionarPacienteView extends javax.swing.JFrame {
    PacienteTableModel paciente_table_model;

    public SelecionarPacienteView(PacienteTableModel paciente_table_model) {
        this.paciente_table_model = paciente_table_model;
        initComponents();
    }

    public PacienteTableModel getPaciente_table_model() {
        return paciente_table_model;
    }

    public void setPaciente_table_model(PacienteTableModel paciente_table_model) {
        this.paciente_table_model = paciente_table_model;
    }

    public JButton getjButton_cancelar() {
        return jButton_cancelar;
    }

    public void setjButton_cancelar(JButton jButton_cancelar) {
        this.jButton_cancelar = jButton_cancelar;
    }

    public JButton getjButton_salvar() {
        return jButton_salvar;
    }

    public void setjButton_salvar(JButton jButton_salvar) {
        this.jButton_salvar = jButton_salvar;
    }

    public JTable getjTable_selecionar_paciente() {
        return jTable_selecionar_paciente;
    }

    public void setjTable_selecionar_paciente(JTable jTable_selecionar_paciente) {
        this.jTable_selecionar_paciente = jTable_selecionar_paciente;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_selecionar_paciente = new javax.swing.JTable();
        jButton_salvar = new javax.swing.JButton();
        jButton_cancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable_selecionar_paciente.setModel(paciente_table_model);
        jScrollPane1.setViewportView(jTable_selecionar_paciente);

        jButton_salvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vendor/icons/mouse_add.png"))); // NOI18N
        jButton_salvar.setText("Selecionar");

        jButton_cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vendor/icons/cancel.png"))); // NOI18N
        jButton_cancelar.setText("Cancelar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(jButton_salvar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_cancelar))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_salvar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_cancelar;
    private javax.swing.JButton jButton_salvar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_selecionar_paciente;
    // End of variables declaration//GEN-END:variables
}
